stages:
  - build
  - update_manifest
  - open_MR

##############################################################################
##                              Variables                                   ##
##############################################################################
variables:
  APP_NAME: gitops-demo-app
  CI_REGISTRY_IMAGE: musyu/$APP_NAME
  CD_PROJECT_ID: 992
  CD_CHART_REPO: gitops-demo-chart
  CD_GIT_REPOSITORY: git@gitlab.fdev:kmuguruma/$CD_CHART_REPO.git
  CD_PROJECT_URL: http://gitlab.fdev/kmuguruma/$CD_CHART_REPO
  CD_MANIFEST_FILE: Chart.yaml
  TAG: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  CD_BRANCH_NAME: update-image-tag-$TAG

##############################################################################
##                              Build Image                                 ##
##############################################################################
build_image:
  image:
    name: mgit/base:kaniko-executor-debug-stable
    entrypoint: [""]
  stage: build
  before_script:
    - echo $CI_REGISTRY_IMAGE:$TAG $PWD
    # login
    - echo "{\"auths\":{\"https://index.docker.io/v2/\":{\"auth\":\"${DOCKERHUB_TOKEN}\"}}}" > /kaniko/.docker/config.json
  script:
    # Docker Build && Push image
    - cat Dockerfile
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$TAG
      --build-arg COMMIT_HASH=$CI_COMMIT_SHORT_SHA

##############################################################################
##                              Deployments                                 ##
##############################################################################
update_manifest:
  image: mikefarah/yq:3.3.4
  stage: update_manifest
  variables:
    GIT_STRATEGY: none
  retry: 2
  script:
    # Add SSH key to root
    - mkdir -p /root/.ssh
    - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - apk add --no-ceche openssh
    - ssh-keyscan -H gitlab.fdev > /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/id_rsa
    # Git
    - apk add --no-cache git
    - git config --global user.name $APP_NAME
    - git config --global user.email $APP_NAME"@gitlab.com"
    - git clone --single-branch --branch master $CD_GIT_REPOSITORY
    - cd $CD_CHART_REPO
    - git checkout -b $CD_BRANCH_NAME
    # Update Helm image tag
    - >
      yq write
      --inplace --verbose $CD_MANIFEST_FILE appVersion $TAG
    - cat $CD_MANIFEST_FILE
    - git commit -am "update image tag" && git push origin $CD_BRANCH_NAME
  only:
    - master

open_merge_request:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-mr
  stage: open_MR
  variables:
    GIT_STRATEGY: none
  script:
    - echo $GITLAB_USER_ID
    # Create merge request
    - >
      gitlab_auto_mr
      --source-branch $CD_BRANCH_NAME
      --project-id $CD_PROJECT_ID
      --gitlab-url $CD_PROJECT_URL
      -t master -d $CD_BRANCH_NAME
      -c WIP -r
  only:
    - master
