image:
  name: mgit/base:kaniko-executor-debug-stable
  entrypoint: [""]
stages:
  - build
  - deploy

##############################################################################
##                              Variables                                   ##
##############################################################################
variables:
  APP_NAME: gitops-demo-app
  CI_REGISTRY_IMAGE: musyu/$APP_NAME
  CD_CHART_REPO: gitops-demo-chart
  CD_GIT_REPOSITORY: git@gitlab.fdev:kmuguruma/$CD_CHART_REPO.git
  CD_MANIFEST_FILE: Chart.yaml
  TAG: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA

##############################################################################
##                              Custom Script                               ##
##############################################################################
before_script:
  - echo $CI_REGISTRY_IMAGE:$TAG $PWD
  # login
  - echo "{\"auths\":{\"https://index.docker.io/v2/\":{\"auth\":\"${DOCKERHUB_TOKEN}\"}}}" > /kaniko/.docker/config.json

##############################################################################
##                              Build Image                                 ##
##############################################################################
build_image:
  stage: build
  script:
    # Docker Build && Push image
    - cat Dockerfile
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$TAG
      --build-arg COMMIT_HASH=$CI_COMMIT_SHORT_SHA

##############################################################################
##                              Deployments                                 ##
##############################################################################
update_manifest:
  image: mikefarah/yq:3.3.4
  stage: deploy
  variables:
    GIT_STRATEGY: none
  retry: 2
  before_script: []
  script:
    # Add SSH key to root
    - mkdir -p /root/.ssh
    - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - apk add --no-ceche openssh
    - ssh-keyscan -H gitlab.fdev > /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/id_rsa
    # Git
    - apk add --no-cache git
    - git config --global user.name $APP_NAME
    - git config --global user.email $APP_NAME"@gitlab.com"
    - git clone --single-branch --branch master $CD_GIT_REPOSITORY
    - cd $CD_CHART_REPO
    - git checkout -b update-image-tag-$TAG
    # Update Helm image tag
    - >
      yq write
      --inplace --verbose $CD_MANIFEST_FILE appVersion $TAG
    - cat $CD_MANIFEST_FILE
    - git commit -am "update image tag" && git push origin update-image-tag-$TAG
    # Create MR
    - apk add --no-cache lab
    - lab merge-request -m "update image tag:"$TAG -d
