version: 2.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
          docker-username: $DOCKERHUB_USER
          docker-password: $DOCKERHUB_PASSWORD
      - docker/build:
          image: $DOCKERHUB_USER/gitops-demo-app
          tag: circleci-$CIRCLE_SHA1
      - docker/push:
          image: $DOCKERHUB_USER/gitops-demo-app
          tag: circleci-$CIRCLE_SHA1
orbs:
  docker: circleci/docker@1.5.0
  version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push
