name: CI

on:
  push:
    branches: [master]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  IMAGE_TAG: actions-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: musyu/gitops-demo-app:actions-$IMAGE_TAG
          cache-from: type=registry,ref=musyu/gitops-demo-app:latest
          cache-to: type=inline
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout manifest repo
        uses: actions/checkout@v2
        with:
          repository: forcia/gitops-demo-manifest
          path: gitops-demo-manifest
      - name: Update image tag
        env:
          CD_MANIFEST_FILE: Chart.yaml
        run: |
          git config user.name 'gitops'
          git config user.email 'gitops@users.noreply.github.com'
          snap install yq
          yq write --inplace --verbose $CD_MANIFEST_FILE appVersion $IMAGE_TAG
          cat $CD_MANIFEST_FILE
          git commit -am "update image tag" && git push origin update-image-tag-$IMAGE_TAG
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update image tag
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
          title: "Update image tag $IMAGE_TAG"
          body: |
            Update image tag
            - Updated with build image tag
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      # 成功時はこちらのステップが実行される
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_CHANNEL: zzz_kmuguruma_notice
          SLACK_TITLE: Pipeline Success
          SLACK_USERNAME: github actions notify
          SLACK_ICON: https://github.co.jp/assets/images/features/actions/actions-icon-actions.svg
          SLACK_COLOR: good
      # 失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.1.0
        if: failure()
        env:
          SLACK_CHANNEL: zzz_kmuguruma_notice
          SLACK_TITLE: Pipeline Failure
          SLACK_USERNAME: github actions notify
          SLACK_ICON: https://github.co.jp/assets/images/features/actions/actions-icon-actions.svg
          SLACK_COLOR: danger
