name: ci

on:
  push:
    branches: master

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: musyu/gitops-demo-app:actions-${{ github.sha }}
          cache-from: type=registry,ref=musyu/gitops-demo-app:latest
          cache-to: type=inline
      # 成功時はこちらのステップが実行される
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_CHANNEL: zzz_kmuguruma_notice
          SLACK_TITLE: Test Success
          SLACK_USERNAME: github actions notify
          SLACK_ICON: https://github.co.jp/assets/images/features/actions/actions-icon-actions.svg
          SLACK_COLOR: good
      # 失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.1.0
        if: failure()
        env:
          SLACK_CHANNEL: zzz_kmuguruma_notice
          SLACK_TITLE: Test Failure
          SLACK_USERNAME: github actions notify
          SLACK_ICON: https://github.co.jp/assets/images/features/actions/actions-icon-actions.svg
          SLACK_COLOR: danger
